# Generated by Django 5.2.8 on 2026-05-21 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_alter_clientprofilemodel_company_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Campaign Title')),
                ('budget', models.DecimalField(decimal_places=2, help_text='Budget in INR (₹) as per UI', max_digits=12)),
                ('category', models.CharField(max_length=255)),
                ('deadline', models.DateField(db_index=True, verbose_name='Deadline')),
                ('description', models.TextField(help_text='Describe your campaign goals...')),
                ('status', models.CharField(choices=[(1, 'Live'), (2, 'Closed'), (3, 'Draft')], db_index=True, default=1, max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='authentication.clientprofilemodel')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
