# Generated by Django 5.2.8 on 2026-05-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Live'), (2, 'Closed'), (3, 'Draft')], db_index=True, default=1),
        ),
    ]
