# Generated by Django 5.2.8 on 2026-05-21 12:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='full_name',
            field=models.CharField(blank=type, max_length=50, null=True, verbose_name='Full Name'),
        ),
        migrations.CreateModel(
            name='ClientProfileModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=12)),
                ('industry', models.IntegerField(blank=True, choices=[(1, 'Fashion'), (2, 'Technology'), (3, 'Food & Beverage'), (4, 'Health & Wellness'), (5, 'Beauty'), (6, 'Sports'), (7, 'Travel'), (8, 'Finance'), (9, 'Other')], null=True)),
                ('company_size', models.IntegerField(blank=True, choices=[(1, '1–10 employees'), (2, '11–50 employees'), (3, '51–200 employees'), (4, '200+ employees')], null=True)),
                ('brand_description', models.TextField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=500, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/')),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates if the brand has the Verified badge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
                'ordering': ['user'],
            },
        ),
    ]
