# Generated by Django 5.2.8 on 2026-05-21 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_usermodel_full_name_clientprofilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='company_size',
            field=models.IntegerField(choices=[(1, '1–10 employees'), (2, '11–50 employees'), (3, '51–200 employees'), (4, '200+ employees')], default=1),
        ),
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='industry',
            field=models.IntegerField(choices=[(1, 'Fashion'), (2, 'Technology'), (3, 'Food & Beverage'), (4, 'Health & Wellness'), (5, 'Beauty'), (6, 'Sports'), (7, 'Travel'), (8, 'Finance'), (9, 'Other')], default=1),
        ),
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Brand Logo'),
        ),
    ]
